### ISSUE TITLE
Add "Fully Diluted" Totals to Stakeholder Snapshot Sheet

### ISSUE THREAD

**Issue by pjohnmeyer** [captable/ocx#19]
## Scope
From https://github.com/captable/ocx/files/11265982/OCX.v.0.4.xlsx
![image](https://user-images.githubusercontent.com/122016/233430792-95a721bb-65ac-42bd-bdf9-34936dc954c7.png)
![image](https://user-images.githubusercontent.com/122016/233448206-9f964650-3c0b-4eb2-9c00-961ae6c63540.png)

## Desired outcome
* Fully Diluted Shares total include all _as converted_ holdings (and "Options Remaining for Issuance") highlighted light green above, regardless of security type. Thus, the only columns excluded from this total are the _outstanding_ columns for Preferred Stock (lowlighted grey) _with a conversion ratio != 1.0_. (This should be reflected in the calculations documentation.)
* Calculations here are all in Excel, not in-tool.

## To-Do
- [ ] Determine necessary in-tool calculations and [document](https://docs.google.com/document/d/19iVTJfJxIMr_gQHzMgSAHR6PhCBFEHg0TahjYc8uOac/edit#bookmark=id.elk3tal0dbg) for review and approval
- [ ] ocf-package: Are the necessary OCF Files being processed?
- [ ] model: Are the necessary OCF Objects being consumed?
- [ ] Develop workbook against Model interfaces.
- [ ] Implement actual Model
- [ ] Integrate and test end-to-end

**Comment by daviidy** [comment]
Added in PR #40
