### ISSUE TITLE
Do options that result in preferred stock need to be "converted"?

### ISSUE THREAD

**Issue by pjohnmeyer** [captable/ocx#26]
In v0.4 of the reference Stakeholder Snapshot sheet, the "Stock Options" columns look like this:

![img](https://user-images.githubusercontent.com/122016/233648504-785847f2-7ec5-419d-a31d-3ba36554368d.png)

It is unclear what the behavior should be here if a Stock Plan converts to preferred stock. This depends somewhat on the answers to #25 as well.

A few possible interpretations:

1. We seek out the "winning" common stock by following the same algorithm in #22 and perform the multiplication in-tool. This would be different than how we do stock classes since in those cases we show two columns for outstanding and as-converted.
2. We display two columns, in the same way that we do for preferred stock with non-zero conversion ratios. Only the "as-converted" values would count towards Fully Diluted numbers.
3. Others?

**Comment by JSv4** [comment]
We think your first option make sense here - basically this would just be an additional layer in the tree you diagrammed in #22. We'd propose the same algorithm - traverse the tree to the commons stock with the lowest non-zero vote count. So convert the vested options to the preferred and then traverse the preferred as previously discussed.

**Comment by pjohnmeyer** [comment]
@daviidy it looks like we need to update the calculation and the code for our existing option plan columns to include conversion ratios. Please write a new issue capturing what you believe the requirements are here and add to https://github.com/captable/ocx/milestone/1
