### ISSUE TITLE
How do we choose one target stock class for warrant conversion?

### ISSUE THREAD

**Issue by pjohnmeyer** [captable/ocx#28]
> **⚠️ Note any Warrants implementation in OCX is dependent on the resolution of https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/pull/410**

In v0.4 of the reference Stakeholder Snapshot sheet, the "Stock Warrants" columns look like this:

![image](https://user-images.githubusercontent.com/122016/233656085-3c73fd54-7152-4f46-b519-871b13e5a7cd.png)

However, a single issuance can be linked to multiple stock classes because [Warrant Issuances](https://open-cap-table-coalition.github.io/Open-Cap-Format-OCF/schema_markdown/schema/objects/transactions/issuance/WarrantIssuance/) have multiple possible conversion rights.

In a previous call we determined an algorithm for Preferred->Common, which I documented and elaborated on in #22. It makes sense to me that we would use the same algorithm for consistency, but I wanted to ask the question rather than assume.

**Comment by dbierut** [comment]
It makes sense to me that warrants would follow the same conversion approach/algorithm for the Preferred -> Common, such that the underlying shares could be reflected in the total FD column when known. 

I think the added wrinkle is that warrants may also need an 'unspecified' conversion option, to cover the cases where the warrants are exercisable for a series of stock and/or at a price still TBD (and I think we do have that as a line item in OCX v0.5 Convertible Securities table).

**Comment by JSv4** [comment]
To the extent the warrant exercise amount is calculable, we'd take the same approach as we did in #22. Where the number of exercisable shares is not known or is an estimate (e.g. a max), you'd have to have some kind of footnote noting this (or, as @dbierut  pointed out, not where the warrants with "unspecified" conversion amounts).

**Comment by pjohnmeyer** [comment]
@daviidy I think in this case we can update https://github.com/captable/ocx/issues/31 with this info and close out this question. Agreed?

**Comment by daviidy** [comment]
> #31

I agree
